services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    FH\Bundle\CookieGuardBundle\Twig\CookieGuardExtension:
        bind:
            $cookieName: '%fh_cookie_guard.cookie_name%'
        tags:
            - { name: twig.extension }
