services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    FH\Bundle\CookieGuardBundle\Twig\CookieGuardExtension:
        $cookieName: '%fh_cookie_guard.cookie_name%'
