services:
    _defaults:
        autowire: true
        autoconfigure: true

    FH\Bundle\CookieGuardBundle\Twig\CookieGuardExtension:
        arguments:
            $cookieName: '%fh_cookie_guard.cookie_name%'
